version: '2'

services:
  mongo:
    image: mongo:3
    ports:
      - 27017:27017
    volumes:
      - ./mongo/dump/:/data/dbmongo
      # mongorestore --nsInclude '*'  --db dbmongo  /data/dbmongo
    environment:
      - MONGODB_DATABASE=dbmongo
      - MONGODB_USER=dbuser
      - MONGODB_PASS=123456

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=dbmysql
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root

  app:
    build: .
    depends_on:
      - mysql
      - mongo
    volumes:
      - .:/app
    working_dir: /app
    # command: php index.php